### ISSUE TITLE
FTB Quests的本地化键名

### ISSUE THREAD

**Issue by lrcno6** [HaloSense/create_astral_translation_zhcn#1]
你好，我也在2.0发布的第一时间开始了整合包的汉化
看到你的进度比我更快，我感到自愧不如
但我要提醒一点：我已经跟Lasky提出要FTB Quests的本地化键名了，大概在下个release的Quests会是基于本地化键名的
以上
本地化键名生成mod：https://modrinth.com/mod/ftbqlocalizationkeys-reconverted/

**Comment by HaloSense** [comment]
好的，我之后会检查本地化键名。

**Comment by HaloSense** [comment]
之后的话可以合作完成文本到本地化键名的迁移

**Comment by lrcno6** [comment]
https://github.com/Laskyyy/Create-Astral/pull/11 本地化键名已生成
任务和现在的发布版2.0.b是完全一致的
