### ISSUE TITLE
补充部分模组的翻译以及 KubeJS 的 startup.js 翻译

### ISSUE THREAD

**Issue by spaceskynet** [HaloSense/create_astral_translation_zhcn#2]
## 自翻了一部分 mod

GearReborn、searchlight、custommachinery、catwalksinc、phonos、itemfilters、adoptafloppa、libraryferret

## 对于forge和fabric版均有的mod，从i18n仓库和mod的仓库找到了翻译，并自己修复了一部分的有

another_furniture、dustrial_decor、automobility、naturalist、doodas、ad_astra

## 其它

ad astra 我查看了一下官方的mod仓库，有人已经提交翻译的pr并且合并到主分支里了，可以使用，指南书部分我二进制比较了一下，1.0.2和1.0.5的内容没有差别，冰焰的指南书翻译可以使用，但是冰焰的翻译和官方仓库KrLite的翻译有部分译名差别，如果要精修还需要费工夫.

KubeJS 的 startup.js 大部分是根据 Mc2deM 1.2版本的翻译，仅补充上了新版没有的部分.

PS：前段时间正好在弄 1.2 版本的补充汉化，刚发了专栏没多久，2.0 版本就出来了，不过有些mod也没变，1.2的翻译可以继续使用

**Comment by lrcno6** [comment]
你这不应该投PR吗...

**Comment by spaceskynet** [comment]
> 你这不应该投PR吗...

刚整理好……现在投了……
