### ISSUE TITLE
挑错，以及申请工作

### ISSUE THREAD

**Issue by KeithTsao** [HaloSense/create_astral_translation_zhcn#23]
v2.0/hard_coding/startup.json

>  "Texture courtesy of Create: Alloyed!": "纹理由 Create 提供：合金化质感！",
>     "Texture courtesy of Jamiscus!": "纹理由 Jamiscus 提供！",
>     "Texture from Create: Things & Misc!": "来自 Create 的纹理：包含物品和杂项！",

这里的[Create: Alloyed!](https://www.mcmod.cn/class/6965.html) 和 [Create: Things & Misc!](https://www.mcmod.cn/class/7464.html)是mod名称不应拆开处理。不过下面这条在最新版整合包里已经没了。

我可以处理最新版startup.js 479行~522行的tooltips

**Comment by HaloSense** [comment]
收到
